### ISSUE TITLE
Citra is still slow please fix it thanks for your hard work can you make it smooth

### ISSUE THREAD

**Issue by qais6666** [weihuoya/citra#171]

**Comment by faroukabd000** [comment]
I think he stopped the development of citra

**Comment by aecarvalho** [comment]
https://github.com/weihuoya/citra/issues/170#issue-733761932
Please do no make copies of the same issue as it will make it more difficult for the developer to tackle other relevant issues.

Also please understand that Mediatek, Exynos and Kirin chips are affected because of the Mali GPUs used in them, Mali GPUs are not good at handling 3D graphics, you can check the relative speeds to Snapdragon by watching Speed Test G videos which very accurately show the large performance gap especially in the GPU performance area.
