### ISSUE TITLE
Fmv hack Resident evil revelation cutscene not syncing with audio, please fix this and release citra soon

### ISSUE THREAD

**Issue by ajay9634** [weihuoya/citra#232]

**Comment by ajay9634** [comment]
My device is realme c3, Helio g70

**Comment by stizzo1** [comment]
Man, you are the only one who is complaining with dozens of posts.

What's more, with one of the worst SoC's out there for emulation.

Do one thing, buy a 3DS.

SnapDragon 855.

**Comment by ajay9634** [comment]
Why should I buy 3ds?  few 2ds games are best and I haven't enough money to buy 3ds or Snapdragon. I waited so long to play 3ds game in mali.finaly it is playing most of game. So should I buy snapdragon.i am not fool.
I am posting issue because developer working on low end device. And I am not complaining. I am happy about its progress.

**Comment by stizzo1** [comment]
You might even be right, if it weren't for the fact that your hardware can't handle emulation. (also because of the painful drivers and the strong hardware limitations and thermal dissipation problems)
Contributing to the community also needs a minimum of technical knowledge.
This is demonstrated by my SoC and the latest build; increased performance here, no bugs, no thermal problems, no regression.

Thanks anyway for your efforts.

PS: a used 3DS costs very little today.
