### ISSUE TITLE
Make the emulator playable in split screen

### ISSUE THREAD

**Issue by shabbirmahmud** [weihuoya/citra#259]
It would be nice if we can edit the buttons and custom layouts for different orientation and split screen.Like in portrait the button and layouts position and configuration will be different from landscape and split screen.It would be very helpful for pokemon games to trade between myself in split screen.

![Screenshot_2021-04-06-16-52-53-70_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/47573399/113700455-ae952d80-96f8-11eb-8393-6833a2071e7d.jpg)

As you can see in the screenshot.If i edit the buttons and layouts for portrait screen then i need to edit it for split screen again.Same goes for landscape screen.

**Comment by shabbirmahmud** [comment]
Thanks for the different configuration for buttons and layouts in protraite and landscape orientation.Bt i hope to see it for split screen.Cz it is very helpful when trade with myself in pokemon games.Hope you will implement it.
![Screenshot_2021-04-08-13-39-47-56_53c01e3b6443161a8deff0f1f7f140ba](https://user-images.githubusercontent.com/47573399/113995617-39e8fd00-9878-11eb-8683-696d2aa28ab7.jpg)

**Comment by aecarvalho** [comment]
Buttons can be edited for both landscape and portrait mode separately, just use another phone to play instead of using split screen because obviously game Devs don't program a game to be played that way as not all android versions and phones support split screen

**Comment by shabbirmahmud** [comment]
> Buttons can be edited for both landscape and portrait mode separately

I know that but I was hoping to see it in split screen too.

>just use another phone to play instead of using split screen

I can do that but it's a hassle to send the save file to another phone and when it's done then send it again in previous phone.

>obviously game Devs don't program a game to be played that way as not all android versions and phones support split screen

I think all the latest Android versions and phones support split screen.

**Comment by aecarvalho** [comment]
> > just use another phone to play instead of using split screen
> 
> I can do that but it's a hassle to send the save file to another phone and when it's done then send it again in previous phone.
> 
You can always trade back to yourself I believe from another instance of the game, basically you want to evolve it then send it back to yourself, you can also do the same with any of your friend connected to the same server.

> > obviously game Devs don't program a game to be played that way as not all android versions and phones support split screen
> 
> I think all the latest Android versions and phones support split screen.
 As I said, developers don't programme a game to be played on split screen specifically, if it was true downscaling then the buttons would be so small that they could be pressed by human fingers without hitting any other controls

**Comment by shabbirmahmud** [comment]
>You can always trade back to yourself I believe from another instance of the game, 

Is citra support two instances on the same emulator on android?

>basically you want to evolve it then send it back to yourself, you can also do the same with any of your friend connected to the same server.

Yeah I can do that.But my friend will knew my pokemon potential and it would be no fun then battle with them.

>As I said, developers don't programme a game to be played on split screen specifically

I just requested.☺️

>it was true downscaling then the buttons would be so small that they could be pressed by human fingers without hitting any other controls

Well I didn't understand what j said.Do you mean the button will become small and I could not be pressed the touch screen?I can manage that and I can use 'hide input buttons' when necessary.

**Comment by aecarvalho** [comment]
> Is citra support two instances on the same emulator on android?

Obviously, use dual apps or Parallel Space


> 
> Yeah I can do that.But my friend will knew my pokemon potential and it would be no fun then battle with them.

That's the silliest comment I've heard all day, is the rest of your Pokémon that useless? The whole part of trading started because Pokémon company wanted the gamers to make real friends beside just playing the game all solo and also as a sales tactic to make people buy both versions of a particular title so that version exclusive Pokémon could be traded, example some of the Ultra Sun Pokémon on Pokémon Ultra Moon.

> I just requested.☺️

I'm just telling that it's most probably not going to happen, we haven't seen split screen emulation perfected to have the exact same layout even on Drastic DS, which is probably one of the most stable ones out there, issues should be focused on reporting problems with the emulation itself and any other game related glitch, split screen related issue is as good as ignored because it's not part of making an emulator work properly


> Well I didn't fully understand whatu said.Do you mean the button will become small and I could not be pressed the touch screen?I can manage that and I can use 'hide input buttons' when necessary.

If you're hiding the input then how will you do the trade?

**Comment by aecarvalho** [comment]
> Is citra support two instances on the same emulator on android?

Obviously, use dual apps or Parallel Space


> 
> Yeah I can do that.But my friend will knew my pokemon potential and it would be no fun then battle with them.

That's the silliest comment I've heard all day, is the rest of your Pokémon that useless? The whole part of trading started because Pokémon company wanted the gamers to make real friends beside just playing the game all solo and also as a sales tactic to make people buy both versions of a particular title so that version exclusive Pokémon could be traded, example some of the Ultra Sun Pokémon on Pokémon Ultra Moon.

> I just requested.☺️

I'm just telling that it's most probably not going to happen, we haven't seen split screen emulation perfected to have the exact same layout even on Drastic DS, which is probably one of the most stable ones out there, issues should be focused on reporting problems with the emulation itself and any other game related glitch, split screen related issue is as good as ignored because it's not part of making an emulator work properly


> Well I didn't fully understand whatu said.Do you mean the button will become small and I could not be pressed the touch screen?I can manage that and I can use 'hide input buttons' when necessary.

If you're hiding the input then how will you do the trade?

**Comment by shabbirmahmud** [comment]
>Obviously, use dual apps or Parallel Space

I know that.I am using island app to create a different space in android and then clone the emu.I was talking about is it possible to run 2 intaces/rom on the same emulator simultaneously like my boy emulator?

>That's the silliest comment I've heard all day, is the rest of your Pokémon that useless? The whole part of trading started because Pokémon company wanted the gamers to make real friends beside just playing the game all solo and also as a sales tactic to make people buy both versions of a particular title so that version exclusive Pokémon could be traded, example some of the Ultra Sun Pokémon on Pokémon Ultra Moon.

Nvm I was talking about competitive pokemon.I also love to trade and battle with others.But it would be no fun if I show my friends my competitive pokemon potential.I want to trade them personally.

Yeah I also want to trade my legends from pokemon ultra moon to ultra sun.Though I can use two phones to trade or use pokehex but it's a hassle to copy the save file on anther phone then trade and then take it back to the previous phone.

>I'm just telling that it's most probably not going to happen, we haven't seen split screen emulation perfected to have the exact same layout even on Drastic DS, which is probably one of the most stable ones out there, issues should be focused on reporting problems with the emulation itself and any other game related glitch, split screen related issue is as good as ignored because it's not part of making an emulator work properly

I understand what I said.So sad☹️.

Bro I checked that drastic emulator layouts and button inputs on split screen.It's well configured.You can check.Maybe it is possible to manually customize it.

>If you're hiding the input then how will you do the trade?

Bro I said when necessary.When I need to touch the touch screen I will hide the input.

**Comment by aecarvalho** [comment]
> I know that.I am using island app to create a different space in android and then clone the emu.I was talking about is it possible to run 2 intaces/rom on the same emulator simultaneously like my boy emulator?

Not for this emulator anyway, and it's not possible to programme such a feature unless you have Snapdragon 855 or above, even playing one instance is making you rely on FPS/speed cheat


> Nvm I was talking about competitive pokemon.I also love to trade and battle with others.But it would be no fun if I show my friends my competitive pokemon potential.I want to trade them personally.

You mean to say you'll lose the battle just because you'll show the Pokémon you're going to trade? I hope you understand that while trading you don't have to show your entire team to anyone, and you also don't strictly have to play with the traded Pokémon with the same person. That's just bad competitive battling skills.

> Bro I checked that drastic emulator layouts and button inputs on split screen.It's well configured.You can check.Maybe it is possible to manually customize it.
> 

I already did, to be more accurate the layout does "change" when switched to split screen relatively which was my point, if you intend to simply ask to make the layout playable in split screen mode then you wouldn't be requesting for "custom layouts"

**Comment by shabbirmahmud** [comment]
Okay okay I understand what I said.Thanks for the information.

>I already did, to be more accurate the layout does "change" when switched to split screen relatively which was my point, if you intend to simply ask to make the layout playable in split screen mode then you wouldn't be requesting for "custom layouts"

Ok then this will do too.Make the emulator playable in split screen.

**Comment by shabbirmahmud** [comment]
Well maybe this not going to happen 😔. I will close this issu.
