### ISSUE TITLE
Internal Reso

### ISSUE THREAD

**Issue by enb77777** [weihuoya/citra#279]
I hope there would be a 1.5 internal resolution option in future updates. Thank you!

**Comment by stizzo1** [comment]
would you like that shit smartphone you bring with you, to simulate the resolution of 600x360? (that is, 1.5 extra frames?¿)

did I get it right?

A toilet of smartphones that can not simulate a resolution 800x480 (2x)???

You seem to me like those idiots who buy a laptop at the supermarket and then they claim a CP2077 with all the filters to the Max. (always with that toilet of laptops that they find themselves)

Well, as humanity we have come to fruit. (I speak of computer and technological ignorance at the highest levels, people who think with the ass and no longer with the brain)

Some nonsensical shots piss me off at the highest level.

Now the toilets also have their value.

**Comment by enb77777** [comment]
Shut up

**Comment by stizzo1** [comment]
Man, why are you talking bullshit?

I have the same smartphone that you claim (but don't) to have.

That's why I get pissed off, reading about your bullshit, simply because on the day you don't know what the fuck to do, except to just spew bullshit.

**Comment by enb77777** [comment]
Hahaha, shut up your stinky mouth.

**Comment by enb77777** [comment]
Gagi ka pla, d nman pr sau bsa k ng bsa.

**Comment by enb77777** [comment]
Ulul

**Comment by enb77777** [comment]
Pkialamero k masydo

**Comment by Pokemetti** [comment]
I don't think that reaction is appropriate stizzo1, if you think that most smartphones can't handle this resolution and are too weak for that job (as of now), that is a fair point, but you just sent multiple paragraphs of hateful and unnecessary rant. Please calm down and at least write in a somehow constructive manner or piss off. I only have two explanations for your current behaviour:
1. You are an adult but very dumb. Solution: try to actually think, if that doesn't help, shut up and don't reproduce so the world doesn't have to suffer from your dumbness in the form of your children anymore.
2. You are a child. Solution: Get out of here and go back to Club Penguin, where Elementary Schoolers belong.

**Comment by Pokemetti** [comment]
I think this proposal is a good idea, though I don't think it should be of any priority.

**Comment by stizzo1** [comment]
It is simply a stupid idea.

I repeat, 1 more frame on hardware that does not allow the emulator to run decently, is not a good idea.

The confusion of many people comes from the fact that they don't know at all the hardware and software of a smartphone and they exchange a Citra emulator with a Dolphin (1.5=960x792 pixels, not native resolution) and they are two completely different hardware, born in different moments.

But you guys are too dumb and ignorant to understand that.

So I'll just tell you to go fuck yourselves as thinking monkeys.

**Comment by enb77777** [comment]
Tang na ka, haybu kp?!

**Comment by enb77777** [comment]
Akla mo sobrang dun0ng at myman emulator dn nmn ang gmit mo bugok!

**Comment by Muzika** [comment]
Guys,

Enough with the trash talks this won't lead to anything other than just annoy the developer when he reads this.

Stizzio1 is technically correct although he could have addressed it in a more proper way to have avoided this conflict.

@enb77777 
That's enough also. Being toxic like that won't help you other than degrading the already low reputation of Filipinos online.

**Comment by enb77777** [comment]
He's the one started it, I was not talking to him. I don't care what other nation think because every nation has their low reputation in some point also. And It won't kill me.

**Comment by Muzika** [comment]
@enb77777 

I understand and just ignore them. The internet is already full of trolls and toxic people. Just don't be another one as there's an oversupply already.


(Don't feed the trolls)

**Comment by enb77777** [comment]
Ok bro

**Comment by stizzo1** [comment]
> Guys,
> 
> Enough with the trash talks this won't lead to anything other than just annoy the developer when he reads this.
> 
> Stizzio1 is technically correct although he could have addressed it in a more proper way to have avoided this conflict.
> 
> @enb77777
> That's enough also. Being toxic like that won't help you other than degrading the already low reputation of Filipinos online.

@Muzika,

As far as I'm concerned, 50% of all "issues" in this github channel, are garbage along with 50% of the trolls that infest the same channel. (I personally invite you to read the almost 300 issues, to get an idea)

I've been following this project since its first day of development and I can recognize when a request is senseless or just for personal venting. (informatical, tecnological and online experiences)

If I were the developer, I would delete most of these "issues" because they are useless, vulgar and offensive to my work.

The problem is that I am not a moderator, otherwise I would have already cleaned up.

In any case, personally I do not make a case of places, cities, states, nations and continents.

Simply of logical consistency and intelligence.

And for that, I have already flagged/reported for trolls and spam this conversation.

With that I end my conversation here, good continuation.

**Comment by Pokemetti** [comment]
Bruh, the reason you're not a moderator is probably because you express yourself in such an offensive way that you can't be distinguished from a troll. Plus, you seem to be offended by simple issues by people who just don't know as much as you about the whole project and are making reasonable proposals (example: this issue). I have seen some other really dumb and offensive issues on this project, but this issue was completely fine imo. I think talking trash about the people just escalates everything, and as @Muzika said, probably annoys the developer. From the few issues I have read on this project I wouldn't be surprised if the developer just ignored them altogether.

**Comment by RaduNastase** [comment]
I don't think .5 increments in resolution would hurt (1.5, 2.5). They would be quite useful in achieving full speeds on certain devices, with a bit of extra shine.
