### ISSUE TITLE
game cover update

### ISSUE THREAD

**Issue by Lorenzo8888** [weihuoya/citra#287]
![IMG_20210504_194924_914](https://user-images.githubusercontent.com/56827114/117047735-7fcba080-ad12-11eb-83fc-146524d690c6.jpg)

**Comment by Lorenzo8888** [comment]
it would be nice to see the game cover like this

**Comment by Tappy-tech** [comment]
> it would be nice to see the game cover like this
If there will be an update like that, there needs to be:

1.

The option to switch between icons and covers, because people have their own likings about Game covers and icons. 

2.

The option to edit the icons and covers, replace them with other pictures of your liking.

3.

Reset to default cover/icon.

**Comment by Lorenzo8888** [comment]
Good !!
