### ISSUE TITLE
Exynos Performance Issues

### ISSUE THREAD

**Issue by some1onLSD** [weihuoya/citra#319]
Bad performance in exynos devices, even with lightweight games like BoxBoy!
Tried it with Exynos 7904 and Exynos 8890, and they both gave a bad performance with poor fps that can't exceed 30 frames and a lot of audio stuttering issues.
-

**Comment by RangerKevin2** [comment]
It depends of the games you're playing, for example, I have the galaxy S10+ with the exynos 9820, most games are running at full speed on x4 resolution but some games like mariokart 7 run at 50% speed on x1 resolution. I'm not a developer but maybe it can be due to the old galaxy 
S7/note 7 exynos driver which is not optimized for emulation or simply the gpu himself not optimized for emulation

**Comment by aecarvalho** [comment]
https://github.com/weihuoya/citra/issues/171#issuecomment-735347907

That sums up the Exynos related issue, basically the GPUs of all older model Exynos, Kirin and Mediatek have been seriously low on graphics performance, so the same reflects in emulated games as well. I would personally advice not to use audio at all, it will always have some glitches in at least some graphics-intensive game locations unless you're using a modern (5nm lithography) flagship device.
