### ISSUE TITLE
metroid samus returns freeze

### ISSUE THREAD

**Issue by xian104** [weihuoya/citra#339]
game runs smoothly, however there is still a random freeze whenever samus moves out of a map to another...

citra mmj 20210628
poco x3 pro snapdragon 860

**Comment by xian104** [comment]
even on the latest update 20210629 there's still some random freezes :(

**Comment by TheOG00** [comment]
Not only metroid many games freeze

**Comment by Tappy-tech** [comment]
Disable New 3DS mode for a workaround.

**Comment by nominka** [comment]
Hello,

Yes random freeze on Kirby epic, Fantasy life, and others.
Disabling the new 3DS mode corrects the problem ?

**Comment by xian104** [comment]
Tried disabling new 3ds mode, it still freezes on samus returns but less
frequent...

**Comment by nominka** [comment]
yes i will make a feedback. which is strange, these games had no problem on the late 2020 releases..

**Comment by weihuoya** [comment]
https://github.com/weihuoya/citra/releases/download/20210630/Citra_MMJ_20210630.apk

**Comment by nominka** [comment]
I had never deactivated: "new 3ds", because I thought it will optimize. now on the 06/29 release, no more freezes and all games run between 15 and 20% faster !! on Mi11 snapdragon 888. I will test the last release. with and without the new mode and I will be back. thank you for your excessive work on Citra and Dolphin .. it's amazing!! 👍

**Comment by xian104** [comment]
Citra_MMJ_20210630 still has the freezing with new 3ds mode on metroid, but disabling new 3ds mode now i think fixed the game
