### ISSUE TITLE
Mario Kart 7 lagging

### ISSUE THREAD

**Issue by jhimwell01** [weihuoya/citra#429]
I'm using Poco X3 Pro (SD 860) and some racetracks running like 40-45 fps with choppy audio on Mario Kart 7 even in the lowest settings. Ex: Luigi's Raceway.

**Comment by Tappy-tech** [comment]
Can you show me the config-mmj.ini file? It's in config folder.

**Comment by jhimwell01** [comment]
It's only Cpu usage limit and New 3DS mode checked and already tried it unchecked

**Comment by Tappy-tech** [comment]
> It's only Cpu usage limit and New 3DS mode checked and already tried it unchecked

Everything else unchecked?

**Comment by jhimwell01** [comment]
I mean from the default settings only those two were changed

**Comment by Tappy-tech** [comment]
> I mean from the default settings only those two were changed

Try disabling CPU Usage Limit. I recommend for you to try checking the usage of your CPU after disabling CPU Usage Limit.

**Comment by RangerKevin2** [comment]
I have the same issue, citra is just unoptimized with mk7, I'm trying to run this game since the first releases of citra
It's apparently not related to snapdragon SOCs because i have the exynos variant of the s10 plus and it's running at a terrible speed. 

You need to wait until citra is fixed for mk7
