### ISSUE TITLE
Massive slowdown when hardware shader disabled.

### ISSUE THREAD

**Issue by DavidAriyan** [weihuoya/citra#457]
Hardware shader need to be disabled for these two games and probably others.
Game 1: Creeping Terror
Game 2: Zero Time Dilemma
![Screenshot_20220211-203322](https://user-images.githubusercontent.com/78215839/153602278-b6595150-c35c-4f59-bb8e-77a6b4e8a023.png)
![Screenshot_20220211-203222](https://user-images.githubusercontent.com/78215839/153602300-afa2a90f-4eb2-4ea6-a374-6e7becc8e09b.png)
![Screenshot_20220211-203423](https://user-images.githubusercontent.com/78215839/153602317-7b1f31d2-197a-4dbf-b0ed-fe815cd3f321.png)
![Screenshot_20220211-203123](https://user-images.githubusercontent.com/78215839/153602335-4c2a06a5-df86-4c79-a4aa-fb1c910436bb.png)

Accurate multiplication doesn't help either.

This bug never got any fix in past years.
I hope someone notice this. These two games need some love.

**Comment by some1onLSD** [comment]
This also happens in "The legend of zelda majora's mask" and "Mario & Sonic Rio 2016 Olympic games", the hardware shaders needs to be disabled in order to work fine without textures jumping around and multiple freezes.

Also disabling hardware shader and using "Skip slow draw" from the game menu produces a black screen.
